package enums;

@:native("BackdropType")
@:build(Macros.nativeNameMod(RemoveTrailingUnderscore, Snakeify, AllCaps))
extern enum BackdropType {
	#if (IsaacVersion == "RepPlus" || IsaacVersion == "Rep" || IsaacVersion == "REPENTOGON")
	Null_;
	Basement;
	Cellar;
	BurntBasement;
	Caves;
	Catacombs;
	FloodedCaves;
	Depths;
	Necropolis;
	DankDepths;
	Womb;
	Utero;
	ScarredWomb;
	BlueWomb;
	Sheol;
	Cathedral;
	DarkRoom;
	Chest;
	MegaSatan;
	Library;
	Shop;
	Isaac;
	Barren;
	Secret;
	Dice;
	Arcade;
	ErrorRoom;
	BlueWombPass;
	GreedShop;
	Dungeon;
	Sacrifice;
	Downpour;
	Mines;
	Mausoleum;
	Corpse;
	Planetarium;
	DownpourEntrance;
	MinesEntrance;
	MausoleumEntrance;
	CorpseEntrance;
	Mausoleum2;
	Mausoleum3;
	Mausoleum4;
	Corpse2;
	Corpse3;
	Dross;
	Ashpit;
	Gehenna;
	Mortis;
	IsaacsBedroom;
	Hallway;
	MomsBedroom;
	Closet;
	ClosetB;
	Dogma;
	DungeonGideon;
	DungeonRotgut;
	DungeonBeast;
	MinesShaft;
	AshpitShaft;
	DarkCloset;
	#end
	#if (IsaacVersion == "RepPlus" || IsaacVersion == "REPENTOGON")
	Deathmatch;
	LilPortal;
	#end
	NumBackdrops;
}
