package enums;

@:native("Card")
@:build(Macros.nativeNameMod(RemoveTrailingUnderscore, Snakeify, Prefix("CARD_"), AllCaps))
extern enum Card {
    Random;
    Null_;
    Fool;
    Magician;
    HighPriestess;
    Empress;
    Emperor;
    Hierophant;
    Lovers;
    Chariot;
    Justice;
    Hermit;
    WheelOfFortune;
    Strength;
    HangedMan;
    Death;
    Temperance;
    Devil;
    Tower;
    Stars;
    Moon;
    Sun;
    Judgement;
    World;
	@:native("CARD_CLUBS_2") TwoOfClubs;
	@:native("CARD_DIAMONDS_2") TwoOfDiamonds;
	@:native("CARD_SPADES_2") TwoOfSpades;
	@:native("CARD_HEARTS_2") TwoOfHearts;
    AceOfClubs;
    AceOfDiamonds;
    AceOfSpades;
    AceOfHearts;
    Joker;
    @:native("RUNE_HAGALAZ") Hagalaz;
    @:native("RUNE_JERA") Jera;
    @:native("RUNE_EHWAZ") Ehwaz;
    @:native("RUNE_DAGAZ") Dagaz;
    @:native("RUNE_ANSUZ") Ansuz;
    @:native("RUNE_PERTHRO") Perthro;
    @:native("RUNE_BERKANO") Berkano;
    @:native("RUNE_ALGIZ") Algiz;
    @:native("RUNE_BLANK") BlankRune;
    @:native("RUNE_BLACK") BlackRune;
    @:native("CARD_CHAOS") ChaosCard;
    @:native("CARD_CREDIT") CreditCard;
    Rules;
    Humanity;
    SuicideKing;
    GetOutOfJail;
    @:native("CARD_QUESTIONMARK") QuestionMark;
    DiceShard;
    EmergencyContact;
    @:native("CARD_HOLY") HolyCard;
    HugeGrowth;
    AncientRecall;
    EraWalk;
    #if (IsaacVersion == REPENTAGON || IsaacVersion == RepPlus || IsaacVersion == Rep)
    @:native("RUNE_SHARD") RuneShard;
    ReverseFool;
    ReverseMagician;
    ReverseHighPriestess;
    ReverseEmpress;
    ReverseEmperor;
    ReverseHeirophant;
    ReverseLovers;
    ReverseChariot;
    ReverseJustice;
    ReverseHermit;
    ReverseWheelOfFortune;
    ReverseStrength;
    ReverseHangedMan;
    ReverseDeath;
    ReverseTemperance;
    ReverseDevil;
    ReverseTower;
    ReverseStars;
    ReverseMoon;
    ReverseSun;
    ReverseJudgement;
    ReverseWorld;
    CrackedKey;
    QueenOfHearts;
    @:native("CARD_WILD") WildCard;
	@:native("CARD_SOUL_ISAAC") SoulOfIsaac;
	@:native("CARD_SOUL_MAGDALENE") SoulOfMaggy;
	@:native("CARD_SOUL_CAIN") SoulOfCain;
	@:native("CARD_SOUL_JUDAS") SoulOfJudas;
	@:native("CARD_SOUL_BLUEBABY") SoulOfBlueBaby;
	@:native("CARD_SOUL_EVE") SoulOfEve;
	@:native("CARD_SOUL_SAMSON") SoulOfSamson;
	@:native("CARD_SOUL_AZAZEL") SoulOfAzazel;
	@:native("CARD_SOUL_LAZARUS") SoulOfLazarus;
	@:native("CARD_SOUL_EDEN") SoulOfEden;
	@:native("CARD_SOUL_LOST") SoulOfTheLost;
	@:native("CARD_SOUL_LILITH") SoulOfLilith;
	@:native("CARD_SOUL_KEEPER") SoulOfTheKeeper;
	@:native("CARD_SOUL_APOLLYON") SoulOfApollyon;
	@:native("CARD_SOUL_FORGOTTEN") SoulOfTheForgotten;
	@:native("CARD_SOUL_BETHANY") SoulOfBethany;
	@:native("CARD_SOUL_JACOB") SoulOfJacob;
    @:native("NUM_CARDS") NumCards;
    #end
}